### ISSUE TITLE
Build Failures with 16.1.0, fixed with revert to 16.0.3

### ISSUE THREAD

**Issue by JKomoroski** [swimlane/ngx-datatable#1864]
**I'm submitting a ...** (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Snippet of Build Error, this list goes on for a long time.
```
ERROR in ../node_modules/@swimlane/ngx-datatable/lib/components/body/body-group-header.directive.d.ts:9:9 - error TS1086: An accessor cannot be declared in an ambient context.

9     get template(): TemplateRef<any>;
          ~~~~~~~~
../node_modules/@swimlane/ngx-datatable/lib/services/column-changes.service.d.ts:8:9 - error TS1086: An accessor cannot be declared in an ambient context.

8     get columnInputChanges$(): Observable<undefined>;
          ~~~~~~~~~~~~~~~~~~~
```

**Expected behavior**
Successful build using 16.1.0 after an update (no breaking changes in a minor version bump).

**Reproduction of the problem**
Updating from 16.0.3 to 16.1.0.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
```
Angular CLI: 8.3.26
Node: 13.6.0
OS: darwin x64
Angular: 8.2.14
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.3.26
@angular/cli                      8.3.26
@ngtools/webpack                  8.2.2
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
```

- **Table version:**
Issue occurs with 16.1.0.
Issue fixed by locking to version 16.0.3

- **Angular version:**
8.3.26

- **Browser:**
N/A

- **Language:**
TS 3.5.3

**Comment by btmurrell** [comment]
we are facing another manifestation today, starting today, getting 16.1.0 on typedoc:
```
Error while generating typedoc file: Error: Command failed: /Users/schme/dev/jones/fubar/node_modules/.bin/typedoc --json /Users/schme/dev/jones/fubar/src/docs-tmp/all.json --tsconfig /Users/schme/dev/jones/fubar/src/app/components/tsconfig.documentation.json /Users/schme/dev/jones/fubar/node_modules/@skope

[TS] stdout: 
Using TypeScript 3.1.6 from /Users/schme/dev/jones/fubar/node_modules/typescript/lib
Error: /Users/schme/dev/jones/fubar/node_modules/@swimlane/ngx-datatable/lib/components/body/body-cell.component.d.ts(7)
 An accessor cannot be declared in an ambient context.
```

**Comment by Siedlerchr** [comment]
Works fine with angular 9. Your Typescript version is too old.
You probably need to add "skilibcheck": true https://stackoverflow.com/a/60294898

**Comment by bacmanni** [comment]
Setting skipLibCheck to true didn't work for us. However as @btmurrell said, removing caret from version number ^16.0.2 and forcing version to be 16.0.2 did the trick.

**Comment by Hypercubed** [comment]
I just republished 16.0.3 as 16.1.1.  Please "upgrade" to 16.1.1 for angular versions <9.  Otherwise please use 17.0.0.

**Comment by ionic4themes** [comment]
> I just republished 16.0.3 as 16.1.1. Please "upgrade" to 16.1.1 for angular versions <9. Otherwise please use 17.0.0.

many thanks, this worked for me. We use Ionic 4 with the following packages versions:

```
    "@angular/core": "^7.2.2",
    "@ionic/angular": "^4.6.2",
    "@swimlane/ngx-datatable": "16.1.1"
```
